#version: '3.1'

#  MYSQL_DATABASE: test_db
#  MYSQL_USER: MYSQL_USER
#  MYSQL_PASSWORD: MYSQL_PASSWORD
# -----
# contnr1: db (mysql) @port:3306
# contnr2: backend (expressjs) @port:4000
# contnr3: frontend (reactjs) @port:3000
# contnr4: nginx (proxy) @port:80
# contnr5: adminer @port:8080
# ------

services:
  db:
    image: mysql
    container_name: db
    restart: always
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpass  # for root user login
     # MYSQL_HOST: localhost
      MYSQL_DATABASE: test_db # creates database automatically
      MYSQL_USER: MYSQL_USER  # for normal user login
      MYSQL_PASSWORD: MYSQL_PASSWORD  # for normal user login


  backend:
    container_name: backend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./backend
    depends_on:
      - db
    ports:
      - 4000:4000 # port defined in index.js, Dockerfile 
    environment:
      MYSQL_HOST: db           # used in index.js
      MYSQL_DATABASE: test_db  # used in index.js
      MYSQL_USER: MYSQL_USER   # used in index.js
      MYSQL_PASSWORD: MYSQL_PASSWORD # used in index.js
  #  volumes:
  #    - /app/node_modules
  #    - ./backend:/app


  frontend:
    container_name: frontend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./frontend
    depends_on:
      - backend
    ports:
      - 3000:3000
    environment:
      - BACKEND_API_URL=http://192.168.0.102:4000 # used in /src/pages/Add.jsx,Books.jsx,Update.jsx
#    volumes:
#      - /app/node_modules
#      - ./frontend:/app



#  nginx-proxy:
#    container_name: nginx-proxy
#    depends_on:
#      - backend
#      - frontend
#    restart: always
#    build:
#      dockerfile: Dockerfile
#      context: ./nginx
#    ports:
#      - 80:80



  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - db
